### Test API Locally
GET http://localhost:7071/api/test

### Send Email from localhost
POST http://localhost:7071/api/sendemail
Content-Type: application/json

{
  "name": "n-string",
  "email": "e-string",
  "subject": "s-string",
  "phone": "p-string",
  "message": "m-string"
}

### Run deployed azure function
GET https://shayon-flask-demo-app.azurewebsites.net/api/test

### Send Email from azure function
POST https://shayon-flask-demo-app.azurewebsites.net/api/sendemail
Content-Type: application/json

{
  "name": "n-string",
  "email": "e-string",
  "subject": "s-string",
  "phone": "p-string",
  "message": "m-string"
}