POST https://j3bvyw3qdpnj4u5yu2kwxo36le0jeifz.lambda-url.ap-southeast-1.on.aws/api/sendemail
Content-Type: application/json

{
  "name": "n-string",
  "email": "e-string",
  "subject": "s-string",
  "phone": "p-string",
  "message": "m-string"
}