import '../globals.scss';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import BodyWrapper from '@/components/layout/BodyWrapper';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Md Samsuzzoha Shayon',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  
  return (
    <html lang="en" >
      <head>
        <title>Md Samsuzzoha Shayon</title>
        <link rel="icon" type="image/x-icon" href='/img/favicon.ico' />
      </head>
      <body className={inter.className} suppressHydrationWarning >
        <BodyWrapper children={children} />
      </body>
    </html>
  )
}
