import Head from 'next/head';
import Footer from '../layouts/Footer';
import Navbar from '../layouts/Navbar';

function withLayout(WrappedComponent) {
  const newElement = () => (
    <div className="withLayout container mx-auto">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="main container mx-auto">
        {/* <h2 className="bg-red-300">Hi there</h2> */}
        <WrappedComponent />
      </main>

      <Footer />
    </div>
  );

  return newElement;
}

export default withLayout;
